### ISSUE TITLE
Alumni Slack Team Invites

### ISSUE THREAD

**Issue by dijonkitchen** [DBC-Boots/DBC-Boots.github.io#1]
Can a sign-up page be hosted on Heroku with Slackin? https://github.com/rauchg/slackin

**Comment by jermspeaks** [comment]
@dijonkitchen Yes, we can totally have a sign up page via Heroku. If you want to take the lead on that, please by all means go ahead. 

I haven't been updating DBC-Boots for a few months now. I would like to open it up for everyone to contribute. I went ahead and added you to the org.

**Comment by dijonkitchen** [comment]
Is this Alumni Slack Team active? I'm currently not in it, so I can't help with a plug-in.

**Comment by jermspeaks** [comment]
Yeah, we're fairly active. I PM'ed you the details via Twitter.

**Comment by dijonkitchen** [comment]
I think I'll leave this be for now since there's already the google doc to distribute and it seems that people want distribution to be on a referral basis.

**Comment by jermspeaks** [comment]
:+1: Sounds good
